version: "3.3"
services:
  mongodb:
    container_name: assignment-database
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    restart: always
volumes:
  mongodb:
