export const POSTGRES_SERVICE = 'POSTGRES_SERVICE';
export const POSTGRES_USER = 'POSTGRES_USER';
export const POSTGRES_TODO = 'POSTGRES_TODO';
export const POSTGRES_AUTH = 'POSTGRES_AUTH';

export const SQLITE_SERVICE = 'SQLITE_SERVICE';
export const SQLITE_USER = 'SQLITE_USER';
export const SQLITE_TODO = 'SQLITE_TODO';
export const SQLITE_AUTH_USER = 'SQLITE_AUTH_USER';

export const AUTH_USER_SERVICE = 'AUTH_USER_SERVICE';
export const AUTH_ADMIN_SERVICE = 'AUTH_ADMIN_SERVICE';
export const AUTH_ENDUSER_FIREBASE_SERVICE = 'AUTH_ENDUSER_FIREBASE_SERVICE';
export const AUTH_ADMIN_FIREBASE_SERVICE = 'AUTH_ADMIN_FIREBASE_SERVICE';