export const NUMBERS = '0123456789';
export const ID_LENGTH = 5;

export const AUTH_CUSTOM_ADMIN_REPOSITORY = 'AUTH_CUSTOM_ADMIN_REPOSITORY';
export const AUTH_CUSTOM_USER_REPOSITORY = 'AUTH_CUSTOM_USER_REPOSITORY';

export const CUSTOM_AUTH_ADMIN_SERVICE = 'AUTH_CUSTOM_ADMIN_SERVICE';
export const CUSTOM_AUTH_USER_SERVICE = 'AUTH_CUSTOM_USER_SERVICE';
